name: Documentation Linting

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Vale
        uses: errata-ai/vale-action@v2.1.1  
        with:
          files: docs
          vale_flags: "--config=.vale.ini"
